In [70]:
import pandas as pd 
import numpy as np

In [71]:
date = pd.read_csv('../sample_data/orders.csv')
time = pd.read_csv('../sample_data/messages.csv')

In [72]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [73]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [74]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [75]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

WORKING WITH DATES

In [76]:
date['date'] = pd.to_datetime(date['date'])

In [77]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

EXTRACT YEAR

In [78]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

2.EXTRACT MONTH

In [79]:
date['date_month_no'] = date['date'].dt.month

In [80]:
date['date_month_name'] = date['date'].dt.month_name()

In [81]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

EXTRACT DAYS

In [82]:
date['date_day'] = date['date'].dt.day

In [83]:
date['date_dow'] = date['date'].dt.dayofweek

In [84]:
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders'],inplace=True)

In [85]:
date['is_weekend'] = np.where(date['date_dow_name'].isin(['Saturday','Sunday']),1,0)

In [86]:
date['date_week'] = date['date'].dt.isocalendar().week

In [87]:
date['quarter'] = date['date'].dt.quarter

In [90]:
date['semester'] = np.where(date['quarter'].isin([1,2]),'Even','Odd')

In [91]:
date.head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,Odd
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,Odd
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,Odd
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,Odd
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,Even

EXTRACT TIME ELAPSED BETWEEM DATES

In [94]:
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 2, 2, 15, 14, 19, 563510)

In [97]:
today - date['date']

0     2246 days 15:14:19.563510
1     2728 days 15:14:19.563510
2     2659 days 15:14:19.563510
3     2361 days 15:14:19.563510
4     2584 days 15:14:19.563510
                 ...
995   2674 days 15:14:19.563510
996   2615 days 15:14:19.563510
997   2463 days 15:14:19.563510
998   2528 days 15:14:19.563510
999   2302 days 15:14:19.563510
Name: date, Length: 1000, dtype: timedelta64[ns]

In [99]:
(today -date['date']).dt.days

0      2246
1      2728
2      2659
3      2361
4      2584
       ...
995    2674
996    2615
997    2463
998    2528
999    2302
Name: date, Length: 1000, dtype: int64

In [104]:
np.round((today - date['date'])/np.timedelta64(1,'D')/30.44)

0      74.0
1      90.0
2      87.0
3      78.0
4      85.0
       ...
995    88.0
996    86.0
997    81.0
998    83.0
999    76.0
Name: date, Length: 1000, dtype: float64

In [105]:
(today - date['date']).dt.days

0      2246
1      2728
2      2659
3      2361
4      2584
       ...
995    2674
996    2615
997    2463
998    2528
999    2302
Name: date, Length: 1000, dtype: int64

In [106]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [ ]:
time['date' ] = pd.to_datetime(time['date'])

In [108]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [115]:
time['hour'] = time['date'].dt.hour
time['min']  = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time['time'] = time['date'].dt.time

In [116]:
time.head(
    
)

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00